"""Generates Base_Stats.txt: a plain-text, hand-editable reference/edit sheet covering every species'
base stats, EXP yield, held items, and level-up learnset. Run from the repo root:

    python3 tools/gen_base_stats_txt.py

Output: Base_Stats.txt (repo root). This file is a REPORT for editing by hand in Notepad - editing it does
NOT change the game by itself; tell the assistant what you changed (or hand back the edited file) and it will
apply the edits to files/poketool/personal/personal.json and files/poketool/personal/wotbl.narc and rebuild.
"""
import json, re, struct

PERSONAL = 'files/poketool/personal/personal.json'
WOTBL = 'files/poketool/personal/wotbl.narc'
OUT = 'Base_Stats.txt'


def defs(path, prefix):
    # BUGFIX: include/constants/moves.h also defines MOVE_ATTRIBUTE_EFFECT=0 .. MOVE_ATTRIBUTE_CONTEST_TYPE=11 -
    # struct-field indices for move data, NOT move IDs - but they match the "MOVE_" prefix and their values (0-11)
    # collide with real low-numbered moves (Pound=1, Karate Chop=2, ... Thunder Punch=9, etc.), so without this
    # guard they silently overwrite those move names in the id->name table below (this is what produced the
    # nonsense "Attribute Range" / "Attribute Priorty" / "Attribute Flags" entries some species showed instead of
    # their real Fire Punch / Ice Punch / Thunder Punch moves - a display bug in this script, not bad game data).
    d = {}
    for line in open(path, encoding='utf-8', errors='replace'):
        m = re.match(r'#define\s+(%s[A-Z0-9_]+)\s+(\d+)\b' % prefix, line)
        if m and 'ATTRIBUTE' not in m.group(1):
            d[int(m.group(2))] = m.group(1)[len(prefix):]
    return d


class Narc:
    def __init__(self, path):
        self.raw = open(path, 'rb').read()
        b = self.raw
        self.btaf = 0x10
        self.count = struct.unpack_from('<H', b, self.btaf + 8)[0]
        btaf_size = struct.unpack_from('<I', b, self.btaf + 4)[0]
        self.btnf = self.btaf + btaf_size
        btnf_size = struct.unpack_from('<I', b, self.btnf + 4)[0]
        self.gmif = self.btnf + btnf_size
        self.data = self.gmif + 8
        self.members = []
        for i in range(self.count):
            s, e = struct.unpack_from('<II', b, self.btaf + 0xC + i * 8)
            self.members.append(bytearray(b[self.data + s:self.data + e]))


def titlecase(const_name):
    """MOVE_DOUBLE_EDGE / ITEM_ORAN_BERRY (prefix already stripped) -> 'Double-Edge' style words."""
    if const_name is None:
        return '???'
    words = const_name.split('_')
    return ' '.join(w.capitalize() for w in words)


move_names = defs('include/constants/moves.h', 'MOVE_')
item_names = defs('include/constants/items.h', 'ITEM_')

# TM01-TM92 then HM01-HM08, in order, from src/item.c's sTMHMMoves[] table.
tmhm_src = open('src/item.c', encoding='utf-8', errors='replace').read()
tmhm_block = re.search(r'static const u16 sTMHMMoves\[\]\s*=\s*\{(.*?)\};', tmhm_src, re.S).group(1)
tmhm_moves = re.findall(r'MOVE_([A-Z0-9_]+)\s*,', tmhm_block)
assert len(tmhm_moves) == 100, 'expected 92 TMs + 8 HMs, got %d' % len(tmhm_moves)
NUM_TMS = 92

wot = Narc(WOTBL)
def parse_learnset(m):
    out = []
    for k in range(0, len(m) - 1, 2):
        v = struct.unpack_from('<H', m, k)[0]
        if v == 0xFFFF:
            break
        out.append((v >> 9, v & 0x1FF))
    return out

pj = json.loads(open(PERSONAL, encoding='utf-8').read())

lines = []
lines.append('BASE STATS / EXP YIELD / HELD ITEMS / LEVEL-UP MOVES / TM-HM MOVES - hand-editable reference')
lines.append('Generated by tools/gen_base_stats_txt.py from the current files/poketool/personal/personal.json')
lines.append('and files/poketool/personal/wotbl.narc. Editing THIS FILE does not change the game by itself -')
lines.append('tell the assistant what you changed, or hand back the edited file, and it will apply the edits and')
lines.append('rebuild. Species #494+ (i.e. index 494 and up in the array) are Gen 4 alternate forms/eggs; the')
lines.append('main 1-493 National Dex entries are listed first, in order.')
lines.append('=' * 100)

for idx, e in enumerate(pj['baseStats']):
    if e['species'] in ('NONE',) and idx != 0:
        continue
    if idx == 0:
        continue  # skip the NONE/index-0 placeholder entry
    name = e['species']
    lines.append('')
    lines.append('#%03d %s' % (idx, name))
    lines.append('-' * 100)
    lines.append('  Base Stats: HP %d / Atk %d / Def %d / SpAtk %d / SpDef %d / Speed %d  (BST %d)' % (
        e['hp'], e['atk'], e['def'], e['spatk'], e['spdef'], e['speed'],
        e['hp'] + e['atk'] + e['def'] + e['spatk'] + e['spdef'] + e['speed']))
    types = [t.replace('TYPE_', '').capitalize() for t in e['types']]
    if types[0] == types[1]:
        types = types[:1]
    lines.append('  Type: %s' % ' / '.join(types))
    lines.append('  Exp Yield: %d' % e['expYield'])
    items = [titlecase(item_names.get(0)) if False else None, None]
    item_disp = []
    for it in e['items']:
        iid = None
        m = re.match(r'ITEM_(.+)', it)
        if it == 'ITEM_NONE':
            item_disp.append('None')
        else:
            item_disp.append(titlecase(it[len('ITEM_'):]))
    lines.append('  Held Items: %s' % ' / '.join(item_disp))

    if idx <= 493:
        ls = parse_learnset(wot.members[idx]) if idx < len(wot.members) else []
        if ls:
            lines.append('  Level-Up Moves:')
            for lvl, mv in ls:
                mv_name = titlecase(move_names.get(mv))
                lines.append('    Lv %-3d %s' % (lvl, mv_name))
        else:
            lines.append('  Level-Up Moves: (none on file / egg-only)')
    else:
        lines.append('  Level-Up Moves: (not tracked here - Gen 4 form/species above #493, uses the base form\'s learnset)')

    tm_list = e.get('tms', [])
    hm_list = e.get('hms', [])
    if tm_list or hm_list:
        lines.append('  TM/HM Moves:')
        for t in tm_list:
            mv_name = titlecase(tmhm_moves[t - 1])
            lines.append('    TM%02d   %s' % (t, mv_name))
        for h in hm_list:
            mv_name = titlecase(tmhm_moves[NUM_TMS + h - 1])
            lines.append('    HM%02d   %s' % (h, mv_name))
    else:
        lines.append('  TM/HM Moves: (none)')

open(OUT, 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
print('Wrote %s (%d species listed)' % (OUT, sum(1 for e in pj['baseStats'][1:] if e['species'] != 'NONE')))
